### ISSUE TITLE
Onlyshown correct language for EN but others like RU and UA isnt! correct

### ISSUE THREAD

**Issue by galaxyvitasa** [unconditional/layin#1]
Hi this is awesome software  but why when i choose Ru or Ua languages  indicator is shown not correct like this  only whork good for EN

https://i.imgur.com/Bb0ghaZ.jpeg
![IMG_20230203_132550866](https://user-images.githubusercontent.com/122528155/216592370-37f407f2-8a04-4e4d-8eec-93d29dd625f7.jpg)

**Comment by extendedzero** [comment]
Edit/create layin.ini file to
[Languages]
EN = 1033;0bb0bb
UA = 1058;5555ff

**Comment by extendedzero** [comment]
> Hi this is awesome software but why when i choose Ru or Ua languages indicator is shown not correct like this only whork good for EN
> 
> https://i.imgur.com/Bb0ghaZ.jpeg ![IMG_20230203_132550866](https://user-images.githubusercontent.com/122528155/216592370-37f407f2-8a04-4e4d-8eec-93d29dd625f7.jpg)

Edit/create layin.ini file to
[Languages]
EN = 1033;0bb0bb
UA = 1058;5555ff
